### ISSUE TITLE
Use ContainerSSH auth library

### ISSUE THREAD

**Issue by ghost** [patsys/containerSSH#1]
Hello,

Thank you again for the [issue reported](https://github.com/containerssh/containerssh/issues/107) with inadequate logging.

Unrelated to that issue, we recommend using the [ContainerSSH auth library](https://github.com/ContainerSSH/auth) and the [config library](https://github.com/ContainerSSH/configuration) to create the auth/config servers in Go.

Feel free to ignore this suggestion. :)

**Comment by patsys** [comment]
Hello @janoszen,

I will change my Code soon to use the Libaries

Thank you

**Comment by patsys** [comment]
Hello @janoszen,

I have change to the Libaries. What is the best way that  all work correct with the RC version.
Same things I found, load the config from files.
- by the config server I get a large json return with many empty fields.
- Config missmatch(possible RC) Documentation, Validate and Output
  - kubernetes.pod.spec validate say unknown.

Thanks for the help, I know this is a RC version

**Comment by ghost** [comment]
@patsys thank you, the documentation has been changed recently to match the code in the main branch. We are working hard to get the next RC out in a few days, I will ping you once it is available. 

As for the `spec` issue, please use `podSpec` for now, that should work with PR3.

**Comment by ghost** [comment]
Updating this issue, PR4 should now match the documentation.

**Comment by patsys** [comment]
Thanks have update the auth and config server  to the new dependencies. I close this issue
